### ISSUE TITLE
Mainline U-Boot Support for RK3588/RK3588S

### ISSUE THREAD

**Issue by efectn** [radxa/u-boot#14]
I've seen stable-5.10-rock5 branch supports RK3588 but it's not supported in mainline uboot. Do you have a plan to send a PR to uboot? I think mainline is always better

**Comment by RadxaYuntian** [comment]
This is Rockchip version of U-Boot based on U-Boot 2017, which is very old and unsuitable for upstreaming. We are unable to produce an independent port of U-Boot at this moment.
